export const types = {
    ADD_TO_HISTORY: "ADD_TO_HISTORY",
    UPDATE_HISTORY: "UPDATE_HISTORY",
    SET_LOCATION: "SET_LOCATION",
    SET_WEATHER: "SET_WEATHER",
    SET_HISTORY: "SET_HISTORY",
    ERROR: "ERROR",
    CLEAR_HISTORY: "CLEAR_HISTORY"
}